// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package queries

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type Kind string

const (
	KindExpenses Kind = "expenses"
	KindInCome   Kind = "in_come"
)

func (e *Kind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Kind(s)
	case string:
		*e = Kind(s)
	default:
		return fmt.Errorf("unsupported scan type for Kind: %T", src)
	}
	return nil
}

type NullKind struct {
	Kind  Kind `json:"kind"`
	Valid bool `json:"valid"` // Valid is true if Kind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullKind) Scan(value interface{}) error {
	if value == nil {
		ns.Kind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Kind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Kind), nil
}

type Item struct {
	ID         int32     `json:"id"`
	UserID     int32     `json:"userId"`
	Amount     int32     `json:"amount"`
	TagIds     []int32   `json:"tagIds"`
	Kind       Kind      `json:"kind"`
	HappenedAt time.Time `json:"happenedAt"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

type Tag struct {
	ID        int32      `json:"id"`
	UserID    int32      `json:"userId"`
	Name      string     `json:"name"`
	Sign      string     `json:"sign"`
	DeletedAt *time.Time `json:"deletedAt"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
}

type User struct {
	ID        int32     `json:"id"`
	Email     string    `json:"email"`
	Phone     string    `json:"phone"`
	Address   string    `json:"address"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type ValidationCode struct {
	ID        int32      `json:"id"`
	Code      string     `json:"code"`
	Email     string     `json:"email"`
	UsededAt  *time.Time `json:"usededAt"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
}
