// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: validation_code.sql

package queries

import (
	"context"
)

const createValidationCode = `-- name: CreateValidationCode :one
INSERT INTO validation_codes(email, code)
  VALUES ($1, $2)
RETURNING
  id, code, email, useded_at, created_at, updated_at
`

type CreateValidationCodeParams struct {
	Email string
	Code  string
}

func (q *Queries) CreateValidationCode(ctx context.Context, arg CreateValidationCodeParams) (ValidationCode, error) {
	row := q.db.QueryRowContext(ctx, createValidationCode, arg.Email, arg.Code)
	var i ValidationCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Email,
		&i.UsededAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
